FROM ubuntu:18.10
# Install required packages and remove the apt packages cache when done
RUN apt-get update && \
    apt-get install -y \
        git \
        openssh-client \
        iputils-ping \
        python3.6 \
        python3-pip \
        sqlite3 \
        && \
    apt-get clean && \
    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

RUN echo [global] > /etc/pip.conf
RUN echo extra-index-url = https://engci-maven.cisco.com/artifactory/api/pypi/yang-suite-dev-pypi/simple >> /etc/pip.conf
RUN pip3 install --upgrade pip
RUN python3.6 -m pip install --upgrade \
    yangsuite \
    yangsuite-filemanager \
    yangsuite-devices \
    yangsuite-yangtree \
    yangsuite-netconf \
    yangsuite-testmanager \
    yangsuite-mapper \
    yangsuite-coverage
EXPOSE "8480"
RUN mkdir -p /home/docker/data
RUN yangsuite --save-settings --configure-only \
    --allowed-hosts 0.0.0.0 localhost 127.0.0.1 \
    --data-path /home/docker/data \
    --settings-module yangsuite.settings.develop
RUN echo "#! /usr/bin/env bash" > /setuser.sh
RUN echo python3 /usr/local/lib/python3.6/dist-packages/yangsuite/manage.py createsuperuser >> /setuser.sh
RUN chmod +x /setuser.sh
